import type { Metadata, Viewport } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'

const inter = Inter({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-inter',
  weight: ['400', '500', '600', '700', '800'],
})

const SITE_URL = 'https://fluxora.marshalx.dev'
const SITE_NAME = 'Fluxora'
const SITE_TITLE = 'Fluxora — Self-Hosted Plex Alternative · Stream Your Media Anywhere'
const SITE_DESC =
  'Open-source media streaming for movies, TV, music, and documents. Self-hosted, zero cloud, LAN-fast at home and seamless over the internet. Free forever — paid tiers from ₹99/mo.'

const KEYWORDS = [
  'self-hosted media server',
  'plex alternative',
  'jellyfin alternative',
  'personal media streaming',
  'home media server',
  'open source streaming',
  'webrtc media streaming',
  'private media library',
  'lan media server',
  'fluxora',
]

export const metadata: Metadata = {
  metadataBase: new URL(SITE_URL),
  title: {
    default: SITE_TITLE,
    template: `%s · ${SITE_NAME}`,
  },
  description: SITE_DESC,
  keywords: KEYWORDS,
  applicationName: SITE_NAME,
  authors: [{ name: 'Marshal', url: 'https://github.com/Marshal-GG' }],
  creator: 'Marshal',
  publisher: 'Marshal',
  category: 'Software',
  classification: 'Media Streaming',
  alternates: {
    canonical: SITE_URL,
  },
  robots: {
    index: true,
    follow: true,
    nocache: false,
    googleBot: {
      index: true,
      follow: true,
      'max-image-preview': 'large',
      'max-snippet': -1,
      'max-video-preview': -1,
    },
  },
  openGraph: {
    type: 'website',
    siteName: SITE_NAME,
    locale: 'en_US',
    url: SITE_URL,
    title: SITE_TITLE,
    description: SITE_DESC,
    // OG card image is auto-generated by `app/opengraph-image.tsx` at build
    // time — Next.js wires it up automatically; no explicit url needed.
  },
  twitter: {
    card: 'summary_large_image',
    title: SITE_TITLE,
    description: SITE_DESC,
    creator: '@MarshalGG',
  },
  icons: {
    icon: [
      { url: '/brand/logo-icon.png', type: 'image/png' },
    ],
    apple: '/brand/logo-icon.png',
  },
  manifest: '/manifest.json',
  formatDetection: {
    email: false,
    address: false,
    telephone: false,
  },
}

export const viewport: Viewport = {
  width: 'device-width',
  initialScale: 1,
  maximumScale: 5,
  themeColor: '#08061A',
  colorScheme: 'dark',
}

// JSON-LD structured data — improves rich-result eligibility on Google.
//
// `aggregateRating` was deliberately removed: fabricating ratings is a
// Google rich-result policy violation and could get the entire site
// demoted. Re-add only when there is a real review source we can point
// at (e.g. AlternativeTo / G2 listing) and a verifiable review count.
const STRUCTURED_DATA = {
  '@context': 'https://schema.org',
  '@graph': [
    {
      '@type': 'Organization',
      '@id': `${SITE_URL}/#organization`,
      name: SITE_NAME,
      url: SITE_URL,
      logo: {
        '@type': 'ImageObject',
        url: `${SITE_URL}/brand/logo-icon.png`,
        width: 512,
        height: 512,
      },
      sameAs: [
        'https://github.com/Marshal-GG/Fluxora-Personal-Streaming-Platform',
      ],
    },
    {
      '@type': 'WebSite',
      '@id': `${SITE_URL}/#website`,
      url: SITE_URL,
      name: SITE_NAME,
      description: SITE_DESC,
      publisher: { '@id': `${SITE_URL}/#organization` },
      inLanguage: 'en-US',
    },
    {
      '@type': 'SoftwareApplication',
      '@id': `${SITE_URL}/#software`,
      name: SITE_NAME,
      operatingSystem: 'Windows, macOS, Linux, iOS, Android',
      applicationCategory: 'MultimediaApplication',
      offers: [
        {
          '@type': 'Offer',
          name: 'Fluxora Free',
          price: '0',
          priceCurrency: 'INR',
          description: 'Self-hosted server, all clients, LAN streaming, TMDB metadata.',
        },
        {
          '@type': 'Offer',
          name: 'Fluxora Plus',
          price: '99',
          priceCurrency: 'INR',
          description: 'Internet streaming via WebRTC, 3 simultaneous remote streams, mobile offline downloads.',
        },
        {
          '@type': 'Offer',
          name: 'Fluxora Pro',
          price: '199',
          priceCurrency: 'INR',
          description: 'Hardware transcoding, 10 simultaneous remote streams, client groups, priority support.',
        },
        {
          '@type': 'Offer',
          name: 'Fluxora Ultimate',
          price: '4499',
          priceCurrency: 'INR',
          description: 'One-time payment, lifetime access, unlimited streams, early-access beta features.',
        },
      ],
      publisher: { '@id': `${SITE_URL}/#organization` },
    },
    {
      '@type': 'FAQPage',
      mainEntity: [
        {
          '@type': 'Question',
          name: 'Is Fluxora actually free?',
          acceptedAnswer: {
            '@type': 'Answer',
            text: 'Yes. The Free tier is the full self-hosted server, every client app, LAN streaming, and TMDB metadata. Free forever, no credit card.',
          },
        },
        {
          '@type': 'Question',
          name: 'Do I need to be on the same Wi-Fi as my server?',
          acceptedAnswer: {
            '@type': 'Answer',
            text: 'Only for the Free tier. Plus, Pro, and Ultimate use WebRTC to stream from your home server to wherever you are — no port-forwarding, no VPN, no public IP needed.',
          },
        },
        {
          '@type': 'Question',
          name: 'What media formats are supported?',
          acceptedAnswer: {
            '@type': 'Answer',
            text: 'Common video (MP4, MKV, MOV, AVI), audio (MP3, FLAC, AAC, WAV), and documents (PDF, EPUB, CBZ). FFmpeg transcoding handles the rest.',
          },
        },
        {
          '@type': 'Question',
          name: 'Where is my data stored?',
          acceptedAnswer: {
            '@type': 'Answer',
            text: 'Entirely on your hardware. Fluxora has no cloud accounts and never uploads your media anywhere.',
          },
        },
      ],
    },
  ],
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" className={inter.variable}>
      <head>
        <link rel="preconnect" href="https://image.tmdb.org" crossOrigin="anonymous" />
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{ __html: JSON.stringify(STRUCTURED_DATA) }}
        />
      </head>
      <body className={inter.className}>
        <a href="#main" className="skip-to-content">Skip to main content</a>

        {/* Ambient floating gradient orbs — fixed-position decorative
            elements that drift behind every page section. Sit on z-index:-1
            so they paint below content but above the body bg. */}
        <div className="bg-orb bg-orb-1" aria-hidden="true" />
        <div className="bg-orb bg-orb-2" aria-hidden="true" />
        <div className="bg-orb bg-orb-3" aria-hidden="true" />
        <div className="bg-grid" aria-hidden="true" />

        {children}
      </body>
    </html>
  )
}
