name: fluxora_mobile
description: Fluxora mobile client for iOS and Android
version: 0.1.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  fluxora_core:
    path: ../../packages/fluxora_core
  flutter_bloc: ^8.1.5
  go_router: ^13.0.0
  get_it: ^7.6.7
  better_player: ^0.0.84
  flutter_webrtc: ^0.10.0
  multicast_dns: ^0.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
