$root = 'f:\AI Models\Projects\Fluxora'

function New-Dir($p)       { New-Item -ItemType Directory -Path $p -Force | Out-Null }
function New-File($p, $c) {
    New-Item -ItemType File -Path $p -Force | Out-Null
    if ($c) { Set-Content -Path $p -Value $c -Encoding UTF8 }
}

# ── apps/server ──────────────────────────────────────────────────────────────
New-Dir  "$root/apps/server/database/migrations"
New-Dir  "$root/apps/server/routers"
New-Dir  "$root/apps/server/services"
New-Dir  "$root/apps/server/models"
New-Dir  "$root/apps/server/utils"
New-Dir  "$root/apps/server/tests"

New-File "$root/apps/server/main.py"                              "# Fluxora Server — FastAPI entry point"
New-File "$root/apps/server/config.py"                            "# Pydantic BaseSettings — all configuration"
New-File "$root/apps/server/requirements.txt"                     "fastapi==0.111.0`nuvicorn[standard]==0.29.0`naiosqlite==0.20.0`nzeroconf==0.131.0`naiortc==1.9.0`nhttpx==0.27.0`npython-multipart==0.0.9"
New-File "$root/apps/server/requirements-dev.txt"                 "pytest==8.2.0`npytest-asyncio==0.23.0`nhttpx==0.27.0`nblack==24.4.0`nruff==0.4.0"
New-File "$root/apps/server/fluxora_server.spec"                  "# PyInstaller build spec — generated by: pyi-makespec main.py"
New-File "$root/apps/server/Dockerfile"                           "FROM python:3.11-slim`nWORKDIR /app`nCOPY requirements.txt .`nRUN pip install -r requirements.txt`nCOPY . .`nEXPOSE 8080`nCMD [""uvicorn"", ""main:app"", ""--host"", ""0.0.0.0"", ""--port"", ""8080""]"
New-File "$root/apps/server/README.md"                            "# Fluxora Server`n`nPython FastAPI backend. See /docs/09_backend for architecture."
New-File "$root/apps/server/database/db.py"                       "# SQLite connection, WAL mode init, migration runner"
New-File "$root/apps/server/database/migrations/001_initial.sql"  "-- Initial schema: media_files, libraries, clients, user_settings"
New-File "$root/apps/server/database/migrations/002_sessions.sql" "-- Stream sessions table"
New-File "$root/apps/server/routers/__init__.py"                  ""
New-File "$root/apps/server/routers/auth.py"                      "# POST /auth/pair  POST /auth/approve  DELETE /auth/revoke"
New-File "$root/apps/server/routers/files.py"                     "# GET /files  GET /files/{id}"
New-File "$root/apps/server/routers/library.py"                   "# CRUD /library  POST /library/{id}/scan"
New-File "$root/apps/server/routers/stream.py"                    "# POST /stream/start  POST /stream/stop  GET /hls/{session}/{segment}"
New-File "$root/apps/server/routers/ws.py"                        "# WS /ws/events — real-time stream and client status"
New-File "$root/apps/server/services/__init__.py"                 ""
New-File "$root/apps/server/services/ffmpeg_service.py"           "# FFmpeg subprocess manager — HLS transcoding"
New-File "$root/apps/server/services/library_service.py"          "# Directory scanning + TMDB enrichment"
New-File "$root/apps/server/services/discovery_service.py"        "# mDNS broadcast: _fluxora._tcp.local"
New-File "$root/apps/server/services/auth_service.py"             "# Token generation, pairing approval, validation"
New-File "$root/apps/server/services/webrtc_service.py"           "# STUN/TURN signaling for internet connections"
New-File "$root/apps/server/models/__init__.py"                   ""
New-File "$root/apps/server/models/media_file.py"                 "# MediaFile Pydantic model"
New-File "$root/apps/server/models/library.py"                    "# Library Pydantic model"
New-File "$root/apps/server/models/client.py"                     "# Client Pydantic model"
New-File "$root/apps/server/models/stream_session.py"             "# StreamSession Pydantic model"
New-File "$root/apps/server/models/settings.py"                   "# UserSettings Pydantic model"
New-File "$root/apps/server/utils/__init__.py"                    ""
New-File "$root/apps/server/utils/file_utils.py"                  "# MIME detection, path helpers, file size formatting"
New-File "$root/apps/server/utils/tmdb_client.py"                 "# TMDB REST API wrapper"
New-File "$root/apps/server/tests/__init__.py"                    ""
New-File "$root/apps/server/tests/conftest.py"                    "# pytest fixtures: test DB, async client"
New-File "$root/apps/server/tests/test_auth.py"                   "# Auth endpoint tests"
New-File "$root/apps/server/tests/test_files.py"                  "# File listing tests"
New-File "$root/apps/server/tests/test_library.py"                "# Library CRUD tests"
New-File "$root/apps/server/tests/test_stream.py"                 "# Stream start/stop tests"

# ── apps/mobile ──────────────────────────────────────────────────────────────
foreach ($feature in @('connect', 'library', 'player', 'settings')) {
    foreach ($layer in @('data', 'domain', 'presentation')) {
        $path = "$root/apps/mobile/lib/features/$feature/$layer"
        New-Dir  $path
        New-File "$path/.gitkeep" ""
    }
}
New-Dir  "$root/apps/mobile/lib/core/di"
New-Dir  "$root/apps/mobile/lib/core/router"
New-Dir  "$root/apps/mobile/lib/shared/widgets"
New-Dir  "$root/apps/mobile/lib/shared/theme"
New-Dir  "$root/apps/mobile/test"
New-Dir  "$root/apps/mobile/android"
New-Dir  "$root/apps/mobile/ios"

New-File "$root/apps/mobile/pubspec.yaml"                              "name: fluxora_mobile`ndescription: Fluxora mobile client for iOS and Android`nversion: 0.1.0+1`n`nenvironment:`n  sdk: '>=3.0.0 <4.0.0'`n  flutter: '>=3.10.0'`n`ndependencies:`n  flutter:`n    sdk: flutter`n  fluxora_core:`n    path: ../../packages/fluxora_core`n  flutter_bloc: ^8.1.5`n  go_router: ^13.0.0`n  get_it: ^7.6.7`n  better_player: ^0.0.84`n  flutter_webrtc: ^0.10.0`n  multicast_dns: ^0.3.2`n`ndev_dependencies:`n  flutter_test:`n    sdk: flutter`n  flutter_lints: ^4.0.0"
New-File "$root/apps/mobile/analysis_options.yaml"                     "include: package:flutter_lints/flutter.yaml"
New-File "$root/apps/mobile/README.md"                                 "# Fluxora Mobile`n`nFlutter app for iOS and Android. See /docs/08_frontend for architecture."
New-File "$root/apps/mobile/lib/main.dart"                             "// Fluxora Mobile — entry point"
New-File "$root/apps/mobile/lib/app.dart"                              "// MaterialApp, theme, and router initialisation"
New-File "$root/apps/mobile/lib/core/di/injector.dart"                 "// get_it dependency injection setup"
New-File "$root/apps/mobile/lib/core/router/app_router.dart"           "// go_router route definitions"
New-File "$root/apps/mobile/lib/shared/widgets/media_card.dart"        "// Reusable media file card widget"
New-File "$root/apps/mobile/lib/shared/widgets/status_badge.dart"      "// Online / Idle / Offline badge"
New-File "$root/apps/mobile/lib/shared/widgets/loading_overlay.dart"   "// Full-screen loading overlay"
New-File "$root/apps/mobile/lib/shared/theme/app_theme.dart"           "// ThemeData built from DESIGN.md tokens"
New-File "$root/apps/mobile/test/.gitkeep"                             ""

# ── apps/desktop ─────────────────────────────────────────────────────────────
foreach ($feature in @('dashboard', 'library', 'clients', 'activity', 'transcoding', 'logs', 'settings')) {
    foreach ($layer in @('data', 'domain', 'presentation')) {
        $path = "$root/apps/desktop/lib/features/$feature/$layer"
        New-Dir  $path
        New-File "$path/.gitkeep" ""
    }
}
New-Dir  "$root/apps/desktop/lib/core/di"
New-Dir  "$root/apps/desktop/lib/core/router"
New-Dir  "$root/apps/desktop/lib/shared/widgets"
New-Dir  "$root/apps/desktop/lib/shared/theme"
New-Dir  "$root/apps/desktop/test"
New-Dir  "$root/apps/desktop/windows"
New-Dir  "$root/apps/desktop/macos"
New-Dir  "$root/apps/desktop/linux"

New-File "$root/apps/desktop/pubspec.yaml"                             "name: fluxora_desktop`ndescription: Fluxora desktop control panel for Windows, macOS, and Linux`nversion: 0.1.0+1`n`nenvironment:`n  sdk: '>=3.0.0 <4.0.0'`n  flutter: '>=3.10.0'`n`ndependencies:`n  flutter:`n    sdk: flutter`n  fluxora_core:`n    path: ../../packages/fluxora_core`n  flutter_bloc: ^8.1.5`n  go_router: ^13.0.0`n  get_it: ^7.6.7`n`ndev_dependencies:`n  flutter_test:`n    sdk: flutter`n  flutter_lints: ^4.0.0"
New-File "$root/apps/desktop/analysis_options.yaml"                    "include: package:flutter_lints/flutter.yaml"
New-File "$root/apps/desktop/README.md"                                "# Fluxora Desktop`n`nFlutter control panel for Windows, macOS, and Linux."
New-File "$root/apps/desktop/lib/main.dart"                            "// Fluxora Desktop — entry point"
New-File "$root/apps/desktop/lib/app.dart"                             "// MaterialApp, theme, and router initialisation"
New-File "$root/apps/desktop/lib/core/di/injector.dart"                "// get_it dependency injection setup"
New-File "$root/apps/desktop/lib/core/router/app_router.dart"          "// go_router route definitions"
New-File "$root/apps/desktop/lib/shared/widgets/sidebar.dart"          "// Navigation sidebar — mirrors the control panel nav"
New-File "$root/apps/desktop/lib/shared/widgets/stat_card.dart"        "// Dashboard stat card widget"
New-File "$root/apps/desktop/lib/shared/widgets/data_table.dart"       "// Reusable sortable data table"
New-File "$root/apps/desktop/lib/shared/widgets/status_badge.dart"     "// Online / Idle / Offline badge"
New-File "$root/apps/desktop/lib/shared/theme/app_theme.dart"          "// ThemeData built from DESIGN.md tokens"
New-File "$root/apps/desktop/test/.gitkeep"                            ""

# ── packages/fluxora_core ────────────────────────────────────────────────────
New-Dir  "$root/packages/fluxora_core/lib/entities"
New-Dir  "$root/packages/fluxora_core/lib/network"
New-Dir  "$root/packages/fluxora_core/lib/storage"
New-Dir  "$root/packages/fluxora_core/lib/constants"

New-File "$root/packages/fluxora_core/pubspec.yaml"                    "name: fluxora_core`ndescription: Shared Dart entities, network client, storage, and design tokens`nversion: 0.1.0`n`nenvironment:`n  sdk: '>=3.0.0 <4.0.0'`n`ndependencies:`n  dio: ^5.4.0`n  flutter_secure_storage: ^9.0.0`n  freezed_annotation: ^2.4.1`n`ndev_dependencies:`n  build_runner: ^2.4.0`n  freezed: ^2.5.2`n  json_serializable: ^6.7.1"
New-File "$root/packages/fluxora_core/README.md"                       "# fluxora_core`n`nShared Dart package imported by mobile and desktop apps."
New-File "$root/packages/fluxora_core/lib/fluxora_core.dart"           "// Barrel export — import 'package:fluxora_core/fluxora_core.dart'"
New-File "$root/packages/fluxora_core/lib/entities/media_file.dart"    "// MediaFile entity"
New-File "$root/packages/fluxora_core/lib/entities/library.dart"       "// Library entity"
New-File "$root/packages/fluxora_core/lib/entities/client.dart"        "// Client entity"
New-File "$root/packages/fluxora_core/lib/entities/stream_session.dart" "// StreamSession entity"
New-File "$root/packages/fluxora_core/lib/entities/server_info.dart"   "// ServerInfo entity — returned by GET /api/v1/info"
New-File "$root/packages/fluxora_core/lib/network/api_client.dart"     "// Dio singleton with auth and base URL interceptors"
New-File "$root/packages/fluxora_core/lib/network/endpoints.dart"      "// All API endpoint URL constants"
New-File "$root/packages/fluxora_core/lib/network/api_exception.dart"  "// Typed API error class"
New-File "$root/packages/fluxora_core/lib/storage/secure_storage.dart" "// flutter_secure_storage wrapper — token read / write / delete"
New-File "$root/packages/fluxora_core/lib/constants/app_colors.dart"   "// Color tokens — sourced from DESIGN.md"
New-File "$root/packages/fluxora_core/lib/constants/app_typography.dart" "// TextStyle tokens — sourced from DESIGN.md"
New-File "$root/packages/fluxora_core/lib/constants/app_sizes.dart"    "// Spacing and border-radius tokens — sourced from DESIGN.md"

# ── scripts ───────────────────────────────────────────────────────────────────
New-Dir  "$root/scripts"
New-File "$root/scripts/build_server.ps1"   "# Windows: builds PyInstaller .exe`n# Usage: .\scripts\build_server.ps1"
New-File "$root/scripts/build_server.sh"    "#!/bin/bash`n# Linux/macOS: builds PyInstaller binary`n# Usage: bash scripts/build_server.sh"
New-File "$root/scripts/build_mobile.sh"    "#!/bin/bash`n# Builds Flutter APK and IPA`n# Usage: bash scripts/build_mobile.sh"
New-File "$root/scripts/build_desktop.sh"   "#!/bin/bash`n# Builds Flutter desktop app`n# Usage: bash scripts/build_desktop.sh"
New-File "$root/scripts/release.sh"         "#!/bin/bash`n# Tags version and creates GitHub Release"

# ── .github/workflows ─────────────────────────────────────────────────────────
New-Dir  "$root/.github/workflows"
New-File "$root/.github/workflows/server_ci.yml"  "name: Server CI`non:`n  push:`n    paths:`n      - 'apps/server/**'`njobs:`n  test:`n    runs-on: ubuntu-latest`n    steps:`n      - uses: actions/checkout@v4`n      - uses: actions/setup-python@v5`n        with:`n          python-version: '3.11'`n      - run: pip install -r apps/server/requirements-dev.txt`n      - run: pytest apps/server/tests/ -v"
New-File "$root/.github/workflows/mobile_ci.yml"  "name: Mobile CI`non:`n  push:`n    paths:`n      - 'apps/mobile/**'`n      - 'packages/**'`njobs:`n  test:`n    runs-on: ubuntu-latest`n    steps:`n      - uses: actions/checkout@v4`n      - uses: subosito/flutter-action@v2`n      - run: flutter pub get`n        working-directory: apps/mobile`n      - run: flutter analyze`n        working-directory: apps/mobile`n      - run: flutter test`n        working-directory: apps/mobile"
New-File "$root/.github/workflows/desktop_ci.yml" "name: Desktop CI`non:`n  push:`n    paths:`n      - 'apps/desktop/**'`n      - 'packages/**'`njobs:`n  test:`n    runs-on: ubuntu-latest`n    steps:`n      - uses: actions/checkout@v4`n      - uses: subosito/flutter-action@v2`n      - run: flutter pub get`n        working-directory: apps/desktop`n      - run: flutter analyze`n        working-directory: apps/desktop`n      - run: flutter test`n        working-directory: apps/desktop"

# ── root .gitignore ──────────────────────────────────────────────────────────
New-File "$root/.gitignore" "# Python`n__pycache__/`n*.py[cod]`n*.egg-info/`ndist/`nbuild/`n.venv/`nvenv/`n*.spec.bak`n`n# Flutter`n.dart_tool/`n.flutter-plugins`n.flutter-plugins-dependencies`n*.iml`n.idea/`n.vscode/`nbuild/`n`n# OS`n.DS_Store`nThumbs.db`n`n# Fluxora runtime`n*.db`n*.db-shm`n*.db-wal`n/tmp/fluxora/`n~/.fluxora/"

Write-Host "All folders and files created successfully."
